### PR TITLE
Switch to `Promise` namespace, add `purs-tidy`

### PR DESCRIPTION
**Pull request by garyb**
Can make the initial release after this I think 🙂

### CODE REVIEW

**Review by sigma-andex — APPROVED** [review]
LGTM

**Comment by JordanMartinez** [comment]
In light of the `purs-backend-es` making it now easier to implement other backends, should we still not use the `JS` prefix on the namespace? While there may not be languages that use `Promise` as a name now, will there be in the future?

**Comment by garyb** [comment]
> In light of the `purs-backend-es` making it now easier to implement other backends

It does? It seems pretty ES/JS specialised to me, it's even in the name :smile:... but no, I don't think that would change anything given the points I raised in the other thread. Perhaps the two most compelling:

1. This library is interop glue, not a library people are going to need otherwise. If they're using it, then they're already going to be depending on other JS-specific libraries like the `purescript-web` stuff.
2. The library is called `js-promise`, so even if other backends wanted to implement a `Promise` module and can't provide a suitable implementation for the `foreign` declarations in here, they could just do like a `native-promise` library or whatever and use the `Promise` name there still.

**Comment by JordanMartinez** [comment]
> It does? It seems pretty ES/JS specialised to me, it's even in the name

Not quite. The repo is designed to store two projects: the general backend optimizer and the code-generator specific to JavaScript. The idea was that other backends can be implemented if one writes a codegenerator for a target language. After that's done, one just needs to implement the FFI for core libraries and you've got yourself a working backend. I'm not sure how hard that is to do in practice, but I imagine it's much simpler than what backend maintainer had to do previously.

Regardless, your other points still stand AFAICT.

**Review by JordanMartinez — APPROVED** [review]

**Pull request merged**
